domain_name         = "siwko.org"
domain_soa_email    = "asiwko@siwko.org"

tenancy_ocid        = "ocid1.tenancy.oc1..aaaaaaaasby5y3q74jz6s3hfg6mad4wjszdcsm7jtjxskhnvodjbrycsdo7a"
user_ocid           = "ocid1.user.oc1..aaaaaaaa3wtd666i2ysmhd2sgwn2tn6qpwavuzk3vvohdncv54n5phiw4laa"
fingerprint         = "4e:a9:6f:94:b1:75:f3:db:9d:ba:de:57:3d:d1:a1:f9"
private_key_path    = "~/.oci/oci_api_key.pem"
subnet_ocid         = "ocid1.subnet.oc1.iad.aaaaaaaafppavj2lavuxhpjtwypcoau4k4feu5tznphhxrixnce5jrjhd7ea"
ssh_public_key_path = "/container_shared/ansible/ansible_rsa.pub"
oci_region          = "us-ashburn-1"